# NumPy
Is going to give us a new array class.

In [8]:
import numpy as np

In [9]:
a = [1,2]
b = [3,4]

In [10]:
a + b

[1, 2, 3, 4]

In [11]:
a * 3

[1, 2, 1, 2, 1, 2]

In [12]:
a = np.array([1,2,3,4])

In [13]:
type(a)

numpy.ndarray

In [14]:
a.ndim

1

In [15]:
a.shape

(4,)

This tuple means that there is only one dimension

In [16]:
a = np.array(range(24))

In [17]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
a.reshape((6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Here is modified in place.

In [19]:
a.resize((6,4))

In [20]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Here modified the variable.

In [21]:
a.shape=(6,4)

In [22]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Is the same of reshape.

In [23]:
a = np.array(range(10))

In [24]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a[0]

0

In [26]:
a[-1]

9

In [27]:
a[3:6]

array([3, 4, 5])

In [28]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [29]:
a[3:8:2]

array([3, 5, 7])

In [30]:
a[3:-2:2]

array([3, 5, 7])

In [31]:
a = np.array(range(24)).reshape(6,4)

In [32]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
a[1,2]

6

In [34]:
a[2,1:4]

array([ 9, 10, 11])

In [35]:
a[2,1:4]=-2
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8, -2, -2, -2],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [36]:
a[2,1:4]=[1,2,3]
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  1,  2,  3],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
a[2, :]

array([8, 1, 2, 3])

In [38]:
a[2]

array([8, 1, 2, 3])

In [39]:
a[:,2]

array([ 2,  6,  2, 14, 18, 22])

In [40]:
a = np.random.randint(0, 10, (3, 4))
a

array([[1, 4, 9, 7],
       [2, 4, 1, 4],
       [9, 3, 6, 6]])

In [41]:
b = np.random.randint(0, 10, (3, 4))
b

array([[4, 8, 4, 0],
       [0, 5, 4, 5],
       [9, 5, 4, 4]])

In [42]:
np.add(a,b)

array([[ 5, 12, 13,  7],
       [ 2,  9,  5,  9],
       [18,  8, 10, 10]])

In [43]:
np.dot(a, b.T)

array([[ 72,  91,  93],
       [ 44,  44,  58],
       [ 84,  69, 144]])

In [44]:
np.power(a,b)

array([[        1,     65536,      6561,         1],
       [        1,      1024,         1,      1024],
       [387420489,       243,      1296,      1296]])

In [45]:
np.exp(a)

array([[2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 1.09663316e+03],
       [7.38905610e+00, 5.45981500e+01, 2.71828183e+00, 5.45981500e+01],
       [8.10308393e+03, 2.00855369e+01, 4.03428793e+02, 4.03428793e+02]])

In [46]:
np.equal(a, b)

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [47]:
np.greater_equal(a,b)

array([[False, False,  True,  True],
       [ True, False, False, False],
       [ True, False,  True,  True]])

In [48]:
np.mean(a)

4.666666666666667

In [49]:
np.mean(a, axis=0)

array([4.        , 3.66666667, 5.33333333, 5.66666667])

In [50]:
np.mean(a, axis=1)

array([5.25, 2.75, 6.  ])

In [51]:
np.median(a)

4.0

In [52]:
np.std(a, axis=1)

array([3.03108891, 1.29903811, 2.12132034])