# NumPy
Is going to give us a new array class.

In [1]:
import numpy as np

In [2]:
a = [1,2]
b = [3,4]

In [3]:
a + b

[1, 2, 3, 4]

In [4]:
a * 3

[1, 2, 1, 2, 1, 2]

In [5]:
a = np.array([1,2,3,4])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.ndim

1

In [8]:
a.shape

(4,)

This tuple means that there is only one dimension

In [9]:
a = np.array(range(24))

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
a.reshape((6,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Here is modified in place.

In [12]:
a.resize((6,4))

In [13]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Here modified the variable.

In [14]:
a.shape=(6,4)

In [15]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Is the same of reshape.

In [16]:
a = np.array(range(10))

In [17]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a[0]

0

In [19]:
a[-1]

9

In [20]:
a[3:6]

array([3, 4, 5])

In [21]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
a[3:8:2]

array([3, 5, 7])

In [23]:
a[3:-2:2]

array([3, 5, 7])

In [24]:
a = np.array(range(24)).reshape(6,4)

In [25]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
a[1,2]

6

In [27]:
a[2,1:4]

array([ 9, 10, 11])

In [28]:
a[2,1:4]=-2
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8, -2, -2, -2],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
a[2,1:4]=[1,2,3]
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  1,  2,  3],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
a[2, :]

array([8, 1, 2, 3])

In [31]:
a[2]

array([8, 1, 2, 3])

In [32]:
a[:,2]

array([ 2,  6,  2, 14, 18, 22])

In [33]:
a = np.random.randint(0, 10, (3, 4))
a

array([[8, 9, 0, 7],
       [9, 3, 3, 7],
       [0, 3, 7, 2]])

In [34]:
b = np.random.randint(0, 10, (3, 4))
b

array([[9, 5, 8, 2],
       [5, 9, 3, 3],
       [4, 4, 2, 1]])

In [35]:
np.add(a,b)

array([[17, 14,  8,  9],
       [14, 12,  6, 10],
       [ 4,  7,  9,  3]])

In [36]:
np.dot(a, b.T)

array([[131, 142,  75],
       [134, 102,  61],
       [ 75,  54,  28]])

In [37]:
np.power(a,b)

array([[134217728,     59049,         0,        49],
       [    59049,     19683,        27,       343],
       [        0,        81,        49,         2]])

In [38]:
np.exp(a)

array([[2.98095799e+03, 8.10308393e+03, 1.00000000e+00, 1.09663316e+03],
       [8.10308393e+03, 2.00855369e+01, 2.00855369e+01, 1.09663316e+03],
       [1.00000000e+00, 2.00855369e+01, 1.09663316e+03, 7.38905610e+00]])

In [39]:
np.equal(a, b)

array([[False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [40]:
np.greater_equal(a,b)

array([[False,  True, False,  True],
       [ True, False,  True,  True],
       [False, False,  True,  True]])

In [41]:
np.mean(a)

4.833333333333333

In [42]:
np.mean(a, axis=0)

array([5.66666667, 5.        , 3.33333333, 5.33333333])

In [43]:
np.mean(a, axis=1)

array([6. , 5.5, 3. ])

In [44]:
np.median(a)

5.0

In [45]:
np.std(a, axis=1)

array([3.53553391, 2.59807621, 2.54950976])